name: Build

on: [push, pull_request]

jobs:
  style:
    name: Build from source
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Compiler
      run: sudo apt-get install -y gcc

    - name: Setup CMake
      uses: lukka/get-cmake@v3.21.1

    - name: Build
      run: ./scripts/build.sh
